services:
  - type: web
    name: exam-platform-algeria
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: GROQ_API_KEY
        scope: build
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: DEBUG
        value: "False"
    staticPublicPath: /static
    autoDeploy: true
    serviceTypeDetails:
      disk:
        name: data
        mountPath: /data
        sizeGB: 1
